In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [2]:
file = 'data/county.xlsx'

In [3]:
data = pd.read_excel(file)
data = data.copy()
data.shape

(9120, 24)

In [4]:
data.shape

(9120, 24)

In [5]:
df = data.copy()

In [6]:
# df_2018 = data[data.year==2018]
# df_2017 = data[data.year==2017]
# df_2016 = data[data.year==2016]
# df_2015 = data[data.year==2015]
# df_2014 = data[data.year==2014]

In [7]:
# print("2018",df_2018.shape)
# print("2017",df_2017.shape)
# print("2016",df_2016.shape)
# print("2015",df_2015.shape)
# print("2014",df_2014.shape)

In [8]:
# print("2018",df_2018.isnull().sum())
# print("2017",df_2017.isnull().sum())
# print("2016",df_2016.isnull().sum())
# print("2015",df_2015.isnull().sum())
# print("2014",df_2014.isnull().sum())

In [9]:
# df_2018.isnull().sum()/1898

In [10]:
# #Importing the function
# from pandas_profiling import ProfileReport
# #Generate the report
# profile = ProfileReport(df=df_2018, title=' Pandas Profiling Report', explorative = True)
# profile

In [11]:
# df_2018[df_2018.county_name=="崇明县"]
# df_2018[df_2018.prov_name=="重庆市"].head(1)

In [12]:
# df_2018.gdp.isnull().sum()

In [13]:
# df_2017.gdp.isnull().sum()

In [14]:
# # creating bool series True for NaN values  
# bool_series = pd.isnull(df_2017["gdp"])  
    
# # filtering data  
# # displaying data only with Gender = NaN  
# df_2017[bool_series]

In [15]:
# df_2017.columns

In [16]:
data.county_code_year14.isnull().sum()

0

In [17]:
# df_2018.sort_values("index_aggregate", ascending = False).head(10)

In [18]:
# In Python
# from sklearn.preprocessing import Imputer
# values = mydata.values
# imputer = Imputer(missing_values=’NaN’, strategy=’mean’)
# transformed_values = imputer.fit_transform(values)
# # strategy can be changed to "median" and “most_frequent”

In [19]:
# import numpy as np
# from sklearn.impute import SimpleImputer
# gdp = df_2018[["gdp"]]
# imp = SimpleImputer(missing_values=np.nan, strategy='median')
# df_2018[["gdp"]] = imp.fit_transform(gdp)
# # strategy can be changed to "median" and “most_frequent”

In [20]:
# df_2018.columns

In [21]:
# df_2018.iloc[:,8:].dtypes

In [22]:
# imp = SimpleImputer(missing_values=np.nan, strategy='median')
# df_2018.iloc[:,8:]= imp.fit_transform(df_2018.iloc[:,8:])

In [23]:
# df_2018 = df_2018.fillna(lambda x: x.median())

In [24]:
# df_2018.isnull().sum()

In [25]:
df.loc[df['year'] == 2014, 'credit_investigation'] = 0

In [26]:
df[df.year==2014]["credit_investigation"].unique()

array([0.])

In [27]:
df.isnull().sum()

year                       0
county_name                0
county_code_year14         0
prov_code                  0
prov_name                  0
pref_code                  0
pref_name                  1
index_aggregate            0
coverage_breadth           0
usage_depth                0
payment                    0
insurance                  0
monetary_fund              0
investment                 0
credit                     0
credit_investigation       0
digitization_level         0
flb                     1263
gdp                      520
per_gdp                 3005
urban                   6034
industry                6052
ip                      7558
tradeopeness            6996
dtype: int64

In [28]:
df.shape

(9120, 24)

In [29]:
# should start with 19th columns on per_gdp
import numpy as np
from sklearn.impute import SimpleImputer
def imputer(df):
    imp = SimpleImputer(missing_values=np.nan, strategy='median')
    df.iloc[:,19:] = imp.fit_transform(df.iloc[:,19:])
    return df

for i in df.year.value_counts().index:
    df[df.year==i] = imputer(df[df.year==i])
df.head()

/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
0,2014,万全县,130729,13,河北省,1307,张家口市,44.58,52.42,37.77,...,35.34,0.0,31.04,528889.0,634602.0,27323.0,0.214560,0.432618,0.064318,0.010522
1,2014,万安县,360828,36,江西省,3608,吉安市,44.39,33.21,78.26,...,85.27,0.0,19.80,341328.0,575617.0,27323.0,0.214560,0.361632,0.106056,0.031628
2,2014,万年县,361129,36,江西省,3611,上饶市,47.34,42.86,60.84,...,57.87,0.0,37.63,644512.0,1000000.0,27323.0,0.214560,0.361632,0.106056,0.031628
3,2014,万源市,511781,51,四川省,5117,达州市,41.67,46.64,41.19,...,45.24,0.0,26.13,574068.0,1200000.0,28395.0,0.561833,0.361632,0.078333,0.005540
4,2014,万荣县,140822,14,山西省,1408,运城市,45.07,48.69,44.57,...,62.17,0.0,34.01,359126.0,618199.0,13778.0,0.069839,0.361632,0.106056,0.031628

In [30]:
df.isnull().sum()

year                       0
county_name                0
county_code_year14         0
prov_code                  0
prov_name                  0
pref_code                  0
pref_name                  1
index_aggregate            0
coverage_breadth           0
usage_depth                0
payment                    0
insurance                  0
monetary_fund              0
investment                 0
credit                     0
credit_investigation       0
digitization_level         0
flb                     1263
gdp                      520
per_gdp                    0
urban                      0
industry                   0
ip                         0
tradeopeness               0
dtype: int64

In [31]:
df.shape

(9120, 24)

In [32]:
bool_series = pd.isnull(df["pref_name"])  
    
# filtering data  
# displaying data only with Gender = NaN  
df[bool_series]

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
7850,2018,尼勒克县,654028,65,新疆维吾尔自治区,6540,NaN,90.04,84.31,94.4,...,102.75,95.81,101.03,NaN,NaN,34697.0,0.230346,0.26967,0.193353,0.237948

In [33]:
df[df["pref_code"]==6540].head(1)

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
150,2014,伊宁县,654021,65,新疆维吾尔自治区,6540,伊犁哈萨克自治州,19.75,10.25,32.61,...,42.11,0.0,27.76,710412.0,691583.0,15927.0,0.176879,0.201927,0.106056,0.031628

In [34]:
df.at[7850,"pref_name"] = "伊犁哈萨克自治州"

In [35]:
df.isnull().sum()

year                       0
county_name                0
county_code_year14         0
prov_code                  0
prov_name                  0
pref_code                  0
pref_name                  0
index_aggregate            0
coverage_breadth           0
usage_depth                0
payment                    0
insurance                  0
monetary_fund              0
investment                 0
credit                     0
credit_investigation       0
digitization_level         0
flb                     1263
gdp                      520
per_gdp                    0
urban                      0
industry                   0
ip                         0
tradeopeness               0
dtype: int64

In [36]:
df.shape

(9120, 24)

In [37]:
import numpy as np
from sklearn.impute import SimpleImputer
def imputer(df):
    imp = SimpleImputer(missing_values=np.nan, strategy='median')
    df.iloc[:,17:18] = imp.fit_transform(df.iloc[:,17:18])
    return df

for i in df.year.value_counts().index:
    df[df.year==i] = imputer(df[df.year==i])
df.head()

/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
0,2014,万全县,130729,13,河北省,1307,张家口市,44.58,52.42,37.77,...,35.34,0.0,31.04,528889.0,634602.0,27323.0,0.214560,0.432618,0.064318,0.010522
1,2014,万安县,360828,36,江西省,3608,吉安市,44.39,33.21,78.26,...,85.27,0.0,19.80,341328.0,575617.0,27323.0,0.214560,0.361632,0.106056,0.031628
2,2014,万年县,361129,36,江西省,3611,上饶市,47.34,42.86,60.84,...,57.87,0.0,37.63,644512.0,1000000.0,27323.0,0.214560,0.361632,0.106056,0.031628
3,2014,万源市,511781,51,四川省,5117,达州市,41.67,46.64,41.19,...,45.24,0.0,26.13,574068.0,1200000.0,28395.0,0.561833,0.361632,0.078333,0.005540
4,2014,万荣县,140822,14,山西省,1408,运城市,45.07,48.69,44.57,...,62.17,0.0,34.01,359126.0,618199.0,13778.0,0.069839,0.361632,0.106056,0.031628

In [38]:
df.isnull().sum()

year                      0
county_name               0
county_code_year14        0
prov_code                 0
prov_name                 0
pref_code                 0
pref_name                 0
index_aggregate           0
coverage_breadth          0
usage_depth               0
payment                   0
insurance                 0
monetary_fund             0
investment                0
credit                    0
credit_investigation      0
digitization_level        0
flb                       0
gdp                     520
per_gdp                   0
urban                     0
industry                  0
ip                        0
tradeopeness              0
dtype: int64

In [39]:
df.shape

(9120, 24)

In [40]:
# df.to_csv("data/imputer_fintech.csv")

In [41]:
# gdp_df = pd.read_csv("data/gdp.csv")

In [42]:
# gdp_df

In [43]:
# add new column ,increase percentage
# gdp_df["increase_percent"] = gdp_df["2018"]/gdp_df["2017"]

In [44]:
# gdp_df

In [45]:
# clean_df = pd.read_csv("data/clean_fintech.csv")

In [46]:
# gdp_df.to_csv("data/gdp.csv",index=False)

In [47]:
# gdp = pd.read_csv("data/gdp.csv")

In [48]:
# gdp.Area = gdp.Area+ "省"

In [49]:
# gdp.at[0,"Area"] = "新疆维吾尔自治区"
# gdp.at[1,"Area"] = "宁夏回族自治区"
# gdp.at[5,"Area"] = '西藏自治区'
# gdp.at[9,"Area"] = '广西壮族自治区'
# gdp.at[22,"Area"] = '内蒙古自治区'

In [50]:
# gdp

In [51]:
# df[["prov_code","prov_name"]].nunique()

In [52]:
# from collections import Counter
# list(set(df[["prov_code","prov_name"]]))

In [53]:
# list(set(df["prov_name"]))
# list(set(df["prov_code"]))

In [54]:
# column_values = df[["prov_code","prov_name"]].values.ravel()
# unique_values =  pd.unique(column_values)
# unique_values

In [55]:
# prov_map = {}
# for i in range(0,len(unique_values),2):
#     prov_map[unique_values[i+1]] = unique_values[i]

In [56]:
# prov_map

In [57]:
# gdp["Area_code"] = gdp.Area.map(prov_map)

In [58]:
# gdp.to_csv("data/gdp.csv",index=False)

In [59]:
# new_gdp = pd.read_csv("data/gdp.csv")

In [60]:
# new_gdp.rename(columns={"Area":"prov_name","Area_code":"prov_code"},inplace=True)

In [61]:
# new_gdp
# new_gdp.to_csv("data/gdp.csv",index=False)

In [62]:
# in_gdp = new_gdp[["increase_percent","prov_code"]]
# in_gdp

In [63]:
# df = df.merge(in_gdp, on="prov_code")

In [64]:
# df[df.year==2018].isnull().sum()

In [65]:
# df[df.year==2017].isnull().sum()

In [66]:
# bool_series = pd.isnull(df[df.year==2018]["gdp"])  
    
# # filtering data  
# # displaying data only with gdp = NaN
# df[df.year==2018][bool_series]

In [67]:
# missing_df = df[df.year==2018][bool_series] 
# missing_df.head()

In [68]:
gdp = pd.read_csv("data/gdp.csv")

In [69]:
gdp.head()

  prov_name      2017      2018  increase_percent  prov_code
0  新疆维吾尔自治区  10881.96  12809.39          1.177122         65
1   宁夏回族自治区   3443.56   3510.21          1.019355         64
2       青海省   2624.83   2748.00          1.046925         63
3       甘肃省   7459.90   8104.07          1.086351         62
4       陕西省  21898.81  23941.88          1.093296         61

In [70]:
in_gdp = gdp[["increase_percent","prov_code"]]
in_gdp.head()
df = df.merge(in_gdp, on="prov_code",how="left")

In [71]:
df.shape

(9120, 25)

In [72]:
df.isnull().sum()

year                      0
county_name               0
county_code_year14        0
prov_code                 0
prov_name                 0
pref_code                 0
pref_name                 0
index_aggregate           0
coverage_breadth          0
usage_depth               0
payment                   0
insurance                 0
monetary_fund             0
investment                0
credit                    0
credit_investigation      0
digitization_level        0
flb                       0
gdp                     520
per_gdp                   0
urban                     0
industry                  0
ip                        0
tradeopeness              0
increase_percent          0
dtype: int64

In [73]:
df.shape

(9120, 25)

In [ ]:
# def fill_2018(df):
#     imp = SimpleImputer(missing_values=np.nan, strategy='median')
#     df.iloc[:,17:18] = imp.fit_transform(df.iloc[:,17:18])
#     return df

# for i in df.year.value_counts().index:
#     df[df.year==i] = imputer(df[df.year==i])
# df.head()

In [86]:
bool_series = pd.isnull(df[df.year==2018]["gdp"])  
    
# filtering data  
# displaying data only with gdp = NaN
df[df.year==2018][bool_series]

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness,increase_percent
7355,2018,互助土族自治县,630223,63,青海省,6302,海东市,81.83,71.59,97.48,...,85.98,87.24,1200000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,1.046925
7357,2018,五原县,150821,15,内蒙古自治区,1508,巴彦淖尔市,93.81,89.75,99.96,...,103.31,96.05,1200000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,1.002768
7365,2018,五莲县,371121,37,山东省,3711,日照市,102.85,89.96,121.30,...,118.58,111.92,1600000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,0.917597
7366,2018,井冈山市,360881,36,江西省,3608,吉安市,108.29,91.26,137.47,...,117.24,111.52,1200000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,1.135467
7368,2018,井陉县,130121,13,河北省,1301,石家庄市,105.91,88.35,114.55,...,112.27,148.24,1200000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,0.955265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9099,2018,黎川县,361022,36,江西省,3610,抚州市,104.20,87.46,135.87,...,122.20,101.91,1200000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,1.135467
9101,2018,黑山县,210726,21,辽宁省,2107,锦州市,92.35,82.92,99.14,...,108.75,111.16,1200000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,1.004327
9105,2018,齐河县,371425,37,山东省,3714,德州市,102.44,89.76,118.96,...,115.54,114.29,1900000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,0.917597
9107,2018,龙南县,360727,36,江西省,3607,赣州市,112.07,94.89,142.52,...,122.75,113.50,1200000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,1.135467
9108,2018,龙口市,370681,37,山东省,3706,烟台市,110.76,97.64,132.26,...,124.03,115.00,5800000.0,NaN,34697.0,0.324884,0.26967,0.193353,0.237948,0.917597

In [85]:
bool_series = pd.isnull(df[df.year==2018]["increase_percent"])  
    
# filtering data  
# displaying data only with gdp = NaN
df[df.year==2018][bool_series]

Empty DataFrame
Columns: [year, county_name, county_code_year14, prov_code, prov_name, pref_code, pref_name, index_aggregate, coverage_breadth, usage_depth, payment, insurance, monetary_fund, investment, credit, credit_investigation, digitization_level, flb, gdp, per_gdp, urban, industry, ip, tradeopeness, increase_percent]
Index: []

[0 rows x 25 columns]

In [87]:

for i, row in df.iterrows():
    try:
        if (row["year"]==2018) and np.isnan(row["gdp"]):
            df.loc[i,"gdp"] = (df[(df.county_code_year14 == row["county_code_year14"]) & (df.year==2017)].gdp 
                         * row["increase_percent"]).values[0]
#             print(df.iloc[i,:])
#             break
    except IndexError:
        print(i, row)

7355 year                        2018
county_name              互助土族自治县
county_code_year14        630223
prov_code                     63
prov_name                    青海省
pref_code                   6302
pref_name                    海东市
index_aggregate            81.83
coverage_breadth           71.59
usage_depth                97.48
payment                    34.35
insurance                  83.89
monetary_fund              46.23
investment                 138.6
credit                      94.9
credit_investigation       85.98
digitization_level         87.24
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.04692
Name: 7355, dtype: object
7369 year                        2018
county_name                  亚东县
county_code_year14        540233
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate           106.28
coverage_breadth           87.65
usage_depth               137.18
payment                    96.02
insurance                 112.01
monetary_fund              86.69
investment                157.57
credit                       155
credit_investigation      108.31
digitization_level        111.65
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7369, dtype: object
7385 year                        2018
county_name                  仲巴县
county_code_year14        540232
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            98.96
coverage_breadth            76.3
usage_depth               124.45
payment                    80.63
insurance                 118.05
monetary_fund               73.9
investment                133.45
credit                    140.96
credit_investigation      100.33
digitization_level        127.46
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7385, dtype: object
7502 year                        2018
county_name              化隆回族自治县
county_code_year14        630224
prov_code                     63
prov_name                    青海省
pref_code                   6302
pref_name                    海东市
index_aggregate             73.5
coverage_breadth           62.04
usage_depth                74.91
payment                    31.39
insurance                  66.14
monetary_fund              38.11
investment                 80.61
credit                     81.31
credit_investigation       92.28
digitization_level         108.8
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.04692
Name: 7502, dtype: object
7532 year                        2018
county_name                 南木林县
county_code_year14        540221
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            87.05
coverage_breadth           69.04
usage_depth               107.03
payment                    63.27
insurance                 113.82
monetary_fund              61.35
investment                 112.2
credit                    114.71
credit_investigation      101.91
digitization_level        110.21
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7532, dtype: object
7590 year                        2018
county_name                  吉隆县
county_code_year14        540234
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate           108.94
coverage_breadth           85.61
usage_depth               138.95
payment                    86.44
insurance                  109.6
monetary_fund              88.77
investment                186.26
credit                    143.08
credit_investigation      106.38
digitization_level        131.44
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7590, dtype: object
7783 year                        2018
county_name                  定日县
county_code_year14        540223
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            96.63
coverage_breadth              71
usage_depth               120.67
payment                     70.3
insurance                 109.51
monetary_fund              78.81
investment                138.19
credit                    132.19
credit_investigation       99.02
digitization_level        137.59
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7783, dtype: object
7785 year                        2018
county_name                  定结县
county_code_year14        540231
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            100.6
coverage_breadth           77.21
usage_depth               130.91
payment                    79.69
insurance                  114.7
monetary_fund              82.91
investment                151.99
credit                    145.71
credit_investigation      100.26
digitization_level        122.75
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7785, dtype: object
7863 year                        2018
county_name                  岗巴县
county_code_year14        540237
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            94.55
coverage_breadth           82.06
usage_depth               117.62
payment                    82.69
insurance                 112.33
monetary_fund              83.81
investment                119.74
credit                    131.28
credit_investigation      105.26
digitization_level         93.89
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7863, dtype: object
7919 year                        2018
county_name                  平安县
county_code_year14        630221
prov_code                     63
prov_name                    青海省
pref_code                   6302
pref_name                    海东市
index_aggregate            87.45
coverage_breadth           77.46
usage_depth                97.54
payment                    42.04
insurance                  90.51
monetary_fund              47.38
investment                117.31
credit                    102.65
credit_investigation        95.6
digitization_level        102.12
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.04692
Name: 7919, dtype: object
7968 year                        2018
county_name                  康马县
county_code_year14        540230
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            86.49
coverage_breadth           71.15
usage_depth               110.31
payment                     72.3
insurance                 107.86
monetary_fund              77.73
investment                118.65
credit                    123.41
credit_investigation       80.56
digitization_level         93.88
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 7968, dtype: object
8008 year                        2018
county_name             循化撒拉族自治县
county_code_year14        630225
prov_code                     63
prov_name                    青海省
pref_code                   6302
pref_name                    海东市
index_aggregate            80.08
coverage_breadth           72.09
usage_depth                87.17
payment                    44.52
insurance                  86.41
monetary_fund              33.86
investment                 86.79
credit                     97.69
credit_investigation       101.5
digitization_level         93.57
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.04692
Name: 8008, dtype: object
8066 year                        2018
county_name                  拉孜县
county_code_year14        540225
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            91.33
coverage_breadth           73.99
usage_depth               120.02
payment                    72.24
insurance                 116.76
monetary_fund              69.32
investment                 132.1
credit                    131.87
credit_investigation      102.69
digitization_level         96.49
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8066, dtype: object
8127 year                        2018
county_name                  昂仁县
county_code_year14        540226
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            91.75
coverage_breadth           70.98
usage_depth               115.17
payment                    67.72
insurance                 111.03
monetary_fund              66.72
investment                129.34
credit                    125.28
credit_investigation       99.06
digitization_level        117.76
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8127, dtype: object
8278 year                         2018
county_name             民和回族土族自治县
county_code_year14         630222
prov_code                      63
prov_name                     青海省
pref_code                    6302
pref_name                     海东市
index_aggregate             90.03
coverage_breadth            73.04
usage_depth                106.98
payment                      45.5
insurance                   91.25
monetary_fund                47.1
investment                 134.04
credit                     115.14
credit_investigation        97.88
digitization_level          115.3
flb                       1.2e+06
gdp                           NaN
per_gdp                     34697
urban                    0.324884
industry                  0.26967
ip                       0.193353
tradeopeness             0.237948
increase_percent          1.04692
Name: 8278, dtype: object
8320 year                        2018
county_name                  江孜县
county_code_year14        540222
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            91.77
coverage_breadth            75.7
usage_depth                114.4
payment                    69.98
insurance                 109.42
monetary_fund              68.41
investment                129.19
credit                     124.3
credit_investigation       96.03
digitization_level        103.73
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8320, dtype: object
8562 year                        2018
county_name                  白朗县
county_code_year14        540228
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            82.61
coverage_breadth           70.62
usage_depth               101.09
payment                    60.82
insurance                  109.6
monetary_fund              72.53
investment                 97.11
credit                    110.46
credit_investigation       97.22
digitization_level         88.62
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8562, dtype: object
8691 year                        2018
county_name                 聂拉木县
county_code_year14        540235
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            99.94
coverage_breadth           76.26
usage_depth               124.45
payment                    77.26
insurance                 110.33
monetary_fund              81.22
investment                144.75
credit                    135.32
credit_investigation      102.57
digitization_level         133.6
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8691, dtype: object
8751 year                        2018
county_name                  萨嘎县
county_code_year14        540236
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            97.63
coverage_breadth           79.29
usage_depth               121.19
payment                    81.32
insurance                 112.84
monetary_fund              80.76
investment                119.48
credit                    142.25
credit_investigation       101.4
digitization_level        115.39
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8751, dtype: object
8752 year                        2018
county_name                  萨迦县
county_code_year14        540224
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            79.15
coverage_breadth           72.87
usage_depth               103.91
payment                    69.29
insurance                 105.78
monetary_fund              76.16
investment                104.91
credit                    111.57
credit_investigation       101.7
digitization_level         54.89
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8752, dtype: object
8801 year                        2018
county_name                 谢通门县
county_code_year14        540227
prov_code                     54
prov_name                  西藏自治区
pref_code                   5402
pref_name                   日喀则市
index_aggregate            92.71
coverage_breadth           72.33
usage_depth               113.86
payment                    62.64
insurance                 115.14
monetary_fund              72.94
investment                119.41
credit                    125.32
credit_investigation      102.33
digitization_level        121.58
flb                      1.2e+06
gdp                          NaN
per_gdp                    34697
urban                   0.324884
industry                 0.26967
ip                      0.193353
tradeopeness            0.237948
increase_percent         1.18115
Name: 8801, dtype: object

In [ ]:
# try:
#     for row in df[df.year==2018][bool_series].iterrows():
#         row[1]["gdp"] = (df[(df.county_code_year14 == row[1]["county_code_year14"]) & (df.year==2017)].gdp 
#                          * row[1]["increase_percent"]).values[0]
#         print(row)
#         break
# except IndexError:
#     print(row)

In [77]:
df[(df.year ==2017) & (df.county_code_year14 == 130729)]

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness,increase_percent
5335,2017,万全县,130729,13,河北省,1307,张家口市,99.18,92.04,115.36,...,122.25,93.38,624922.0,666736.0,32202.0,0.2538,0.287401,0.197952,0.025868,0.955265

In [82]:
df[(df.year ==2018) & (df.county_code_year14 == 130729)]

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness,increase_percent
7222,2018,万全县,130729,13,河北省,1307,张家口市,100.18,89.78,115.81,...,112.42,106.13,1200000.0,636909.762519,34697.0,0.324884,0.26967,0.193353,0.237948,0.955265

In [78]:
np.isnan(df[(df.year ==2018) & (df.county_code_year14 == 130729)]['gdp'].values[0])

False

In [84]:
df[(df.year ==2017) & (df.county_code_year14 == 630223)]

Empty DataFrame
Columns: [year, county_name, county_code_year14, prov_code, prov_name, pref_code, pref_name, index_aggregate, coverage_breadth, usage_depth, payment, insurance, monetary_fund, investment, credit, credit_investigation, digitization_level, flb, gdp, per_gdp, urban, industry, ip, tradeopeness, increase_percent]
Index: []

[0 rows x 25 columns]

In [83]:
df.shape

(9120, 25)

In [88]:
df.isnull().sum()

year                     0
county_name              0
county_code_year14       0
prov_code                0
prov_name                0
pref_code                0
pref_name                0
index_aggregate          0
coverage_breadth         0
usage_depth              0
payment                  0
insurance                0
monetary_fund            0
investment               0
credit                   0
credit_investigation     0
digitization_level       0
flb                      0
gdp                     41
per_gdp                  0
urban                    0
industry                 0
ip                       0
tradeopeness             0
increase_percent         0
dtype: int64

In [89]:
import numpy as np
from sklearn.impute import SimpleImputer
def imputer(df):
    imp = SimpleImputer(missing_values=np.nan, strategy='median')
    df.iloc[:,18:19] = imp.fit_transform(df.iloc[:,18:19])
    return df

for i in df.year.value_counts().index:
    df[df.year==i] = imputer(df[df.year==i])
df.head()

/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness,increase_percent
0,2014,万全县,130729,13,河北省,1307,张家口市,44.58,52.42,37.77,...,0.0,31.04,528889.0,634602.0,27323.0,0.214560,0.432618,0.064318,0.010522,0.955265
1,2014,万安县,360828,36,江西省,3608,吉安市,44.39,33.21,78.26,...,0.0,19.80,341328.0,575617.0,27323.0,0.214560,0.361632,0.106056,0.031628,1.135467
2,2014,万年县,361129,36,江西省,3611,上饶市,47.34,42.86,60.84,...,0.0,37.63,644512.0,1000000.0,27323.0,0.214560,0.361632,0.106056,0.031628,1.135467
3,2014,万源市,511781,51,四川省,5117,达州市,41.67,46.64,41.19,...,0.0,26.13,574068.0,1200000.0,28395.0,0.561833,0.361632,0.078333,0.005540,1.160137
4,2014,万荣县,140822,14,山西省,1408,运城市,45.07,48.69,44.57,...,0.0,34.01,359126.0,618199.0,13778.0,0.069839,0.361632,0.106056,0.031628,1.027672

In [90]:
df.isnull().sum()

year                    0
county_name             0
county_code_year14      0
prov_code               0
prov_name               0
pref_code               0
pref_name               0
index_aggregate         0
coverage_breadth        0
usage_depth             0
payment                 0
insurance               0
monetary_fund           0
investment              0
credit                  0
credit_investigation    0
digitization_level      0
flb                     0
gdp                     0
per_gdp                 0
urban                   0
industry                0
ip                      0
tradeopeness            0
increase_percent        0
dtype: int64

In [91]:
df.shape

(9120, 25)

In [92]:
df.drop(columns =["increase_percent"],inplace=True)

In [93]:
df.shape

(9120, 24)

In [94]:
df.to_csv("data/gdp_clean_fintech.csv",index=False)

In [96]:
df.head()

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
0,2014,万全县,130729,13,河北省,1307,张家口市,44.58,52.42,37.77,...,35.34,0.0,31.04,528889.0,634602.0,27323.0,0.214560,0.432618,0.064318,0.010522
1,2014,万安县,360828,36,江西省,3608,吉安市,44.39,33.21,78.26,...,85.27,0.0,19.80,341328.0,575617.0,27323.0,0.214560,0.361632,0.106056,0.031628
2,2014,万年县,361129,36,江西省,3611,上饶市,47.34,42.86,60.84,...,57.87,0.0,37.63,644512.0,1000000.0,27323.0,0.214560,0.361632,0.106056,0.031628
3,2014,万源市,511781,51,四川省,5117,达州市,41.67,46.64,41.19,...,45.24,0.0,26.13,574068.0,1200000.0,28395.0,0.561833,0.361632,0.078333,0.005540
4,2014,万荣县,140822,14,山西省,1408,运城市,45.07,48.69,44.57,...,62.17,0.0,34.01,359126.0,618199.0,13778.0,0.069839,0.361632,0.106056,0.031628

In [95]:
data.head()

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
0,2014,万全县,130729,13,河北省,1307,张家口市,44.58,52.42,37.77,...,35.34,NaN,31.04,528889.0,634602.0,NaN,NaN,0.432618,0.064318,0.010522
1,2014,万安县,360828,36,江西省,3608,吉安市,44.39,33.21,78.26,...,85.27,NaN,19.80,341328.0,575617.0,NaN,NaN,NaN,NaN,NaN
2,2014,万年县,361129,36,江西省,3611,上饶市,47.34,42.86,60.84,...,57.87,NaN,37.63,644512.0,1000000.0,NaN,NaN,NaN,NaN,NaN
3,2014,万源市,511781,51,四川省,5117,达州市,41.67,46.64,41.19,...,45.24,NaN,26.13,574068.0,1200000.0,28395.0,0.561833,NaN,0.078333,0.005540
4,2014,万荣县,140822,14,山西省,1408,运城市,45.07,48.69,44.57,...,62.17,NaN,34.01,359126.0,618199.0,13778.0,0.069839,NaN,NaN,NaN