In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [2]:
file = 'data/county.xlsx'

In [3]:
data = pd.read_excel(file)
data = data.copy()
data.shape

(9120, 24)

In [84]:
data.shape

(9120, 24)

In [85]:
df = data.copy()

In [115]:
df_2018 = data[data.year==2018]
df_2017 = data[data.year==2017]
df_2016 = data[data.year==2016]
df_2015 = data[data.year==2015]
df_2014 = data[data.year==2014]

In [5]:
df_2018.shape

(1898, 24)

In [116]:
print("2018",df_2018.shape)
print("2017",df_2017.shape)
print("2016",df_2016.shape)
print("2015",df_2015.shape)
print("2014",df_2014.shape)

2018 (1898, 24)
2017 (1887, 24)
2016 (1895, 24)
2015 (1720, 24)
2014 (1720, 24)

In [6]:
type(df_2018)

pandas.core.frame.DataFrame

In [7]:
df_2018.isnull().sum()/1898

year                    0.000000
county_name             0.000000
county_code_year14      0.000000
prov_code               0.000000
prov_name               0.000000
pref_code               0.000000
pref_name               0.000527
index_aggregate         0.000000
coverage_breadth        0.000000
usage_depth             0.000000
payment                 0.000000
insurance               0.000000
monetary_fund           0.000000
investment              0.000000
credit                  0.000000
credit_investigation    0.000000
digitization_level      0.000000
flb                     0.649631
gdp                     0.267123
per_gdp                 0.379874
urban                   0.800843
industry                0.787144
ip                      0.962592
tradeopeness            0.971022
dtype: float64

In [30]:
# #Importing the function
# from pandas_profiling import ProfileReport
# #Generate the report
# profile = ProfileReport(df=df_2018, title=' Pandas Profiling Report', explorative = True)
# profile

In [91]:
df_2018[df_2018.county_name=="崇明县"]
df_2018[df_2018.prov_name=="重庆市"]
df_2018.shape

(1898, 24)

In [8]:
df_2018.gdp.isnull().sum()

507

In [9]:
df_2017.gdp.isnull().sum()

7

In [12]:
# creating bool series True for NaN values  
bool_series = pd.isnull(df_2017["gdp"])  
    
# filtering data  
# displaying data only with Gender = NaN  
df_2017[bool_series]

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
5662,2017,即墨市,370282,37,山东省,3702,青岛市,108.13,98.66,135.73,...,147.05,134.72,89.29,8500000.0,NaN,NaN,NaN,NaN,NaN,NaN
5892,2017,定海区,330902,33,浙江省,3309,舟山市,119.78,105.06,156.85,...,169.79,140.01,101.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6158,2017,扎赉诺尔区,150703,15,内蒙古自治区,1507,呼伦贝尔市,100.51,92.96,122.10,...,127.22,121.72,86.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6300,2017,林芝县,542621,54,西藏自治区,5426,林芝地区,110.55,103.18,131.62,...,135.34,124.63,96.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6733,2017,科尔沁区,150502,15,内蒙古自治区,1505,通辽市,102.89,97.07,120.36,...,133.42,126.83,90.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6846,2017,莱山区,370613,37,山东省,3706,烟台市,120.83,110.37,140.48,...,151.45,131.31,119.63,3600000.0,NaN,NaN,NaN,NaN,NaN,NaN
6973,2017,邯郸县,130421,13,河北省,1304,邯郸市,110.26,102.71,128.19,...,139.93,120.94,102.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_2017.columns

Index(['year', 'county_name', 'county_code_year14', 'prov_code', 'prov_name',
       'pref_code', 'pref_name', 'index_aggregate', 'coverage_breadth',
       'usage_depth', 'payment', 'insurance', 'monetary_fund', 'investment',
       'credit', 'credit_investigation', 'digitization_level', 'flb', 'gdp',
       'per_gdp', 'urban', 'industry', 'ip', 'tradeopeness'],
      dtype='object')

In [16]:
data.county_code_year14.isnull()

0

In [34]:
df_2018.sort_values("index_aggregate", ascending = False).head(10)

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
7314,2018,义乌市,330782,33,浙江省,3307,金华市,127.21,111.40,175.40,...,197.42,136.26,91.84,24000000.0,12000000.0,95795.0,NaN,0.279094,NaN,2.033799
8128,2018,昆山市,320583,32,江苏省,3205,苏州市,125.19,109.66,157.96,...,188.45,135.86,116.96,34000000.0,38000000.0,230270.0,NaN,0.509170,NaN,NaN
8742,2018,莱山区,370613,37,山东省,3706,烟台市,124.36,109.46,147.28,...,166.50,132.64,131.90,3500000.0,NaN,NaN,NaN,NaN,NaN,NaN
7784,2018,定海区,330902,33,浙江省,3309,舟山市,124.27,105.05,163.29,...,180.30,133.39,116.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7333,2018,乐清市,330382,33,浙江省,3303,温州市,123.74,103.17,164.76,...,196.35,130.10,117.16,12000000.0,11000000.0,76016.0,NaN,0.387587,NaN,0.144456
8954,2018,闽侯县,350121,35,福建省,3501,福州市,123.55,105.30,159.17,...,189.69,141.25,119.11,3800000.0,6000000.0,83827.0,NaN,0.511076,NaN,NaN
7286,2018,临安市,330185,33,浙江省,3301,杭州市,123.35,103.48,162.26,...,188.24,133.29,118.28,6500000.0,5400000.0,91154.0,NaN,0.392732,NaN,0.222149
8221,2018,桐乡市,330483,33,浙江省,3304,嘉兴市,122.98,105.46,158.27,...,180.16,130.80,116.71,11000000.0,8900000.0,105910.0,NaN,0.466162,NaN,0.321503
8396,2018,洞头县,330322,33,浙江省,3303,温州市,122.69,100.74,166.20,...,196.08,131.11,116.09,844000.0,1000000.0,98685.0,NaN,0.175877,NaN,0.040654
8422,2018,海宁市,330481,33,浙江省,3304,嘉兴市,122.63,105.81,156.54,...,179.47,129.62,116.55,12000000.0,9500000.0,111478.0,NaN,0.495937,NaN,0.535711

In [ ]:
# In Python
# from sklearn.preprocessing import Imputer
# values = mydata.values
# imputer = Imputer(missing_values=’NaN’, strategy=’mean’)
# transformed_values = imputer.fit_transform(values)
# # strategy can be changed to "median" and “most_frequent”

In [58]:
df_2018.head()

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
7222,2018,万全县,130729,13,河北省,1307,张家口市,100.18,89.78,115.81,...,125.00,112.42,106.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7223,2018,万宁市,469006,46,海南省,469006,省直辖县市,108.74,94.44,134.94,...,155.85,120.22,108.36,1500000.0,2200000.0,38940.0,NaN,NaN,NaN,NaN
7224,2018,万安县,360828,36,江西省,3608,吉安市,102.02,84.85,122.55,...,138.75,115.16,121.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7225,2018,万年县,361129,36,江西省,3611,上饶市,104.65,87.49,132.92,...,153.27,116.54,109.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7226,2018,万源市,511781,51,四川省,5117,达州市,100.01,87.19,115.75,...,131.30,111.92,113.78,1100000.0,1400000.0,33836.0,0.412048,NaN,NaN,NaN

In [70]:
import numpy as np
from sklearn.impute import SimpleImputer
# gdp = df_2018[["gdp"]]
# imp = SimpleImputer(missing_values=np.nan, strategy='median')
# df_2018[["gdp"]] = imp.fit_transform(gdp)
# # strategy can be changed to "median" and “most_frequent”

/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())

In [76]:
df_2018.head()

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
7222,2018,万全县,130729,13,河北省,1307,张家口市,100.18,89.78,115.81,...,125.00,112.42,106.13,NaN,1300000.0,NaN,NaN,NaN,NaN,NaN
7223,2018,万宁市,469006,46,海南省,469006,省直辖县市,108.74,94.44,134.94,...,155.85,120.22,108.36,1500000.0,2200000.0,38940.0,NaN,NaN,NaN,NaN
7224,2018,万安县,360828,36,江西省,3608,吉安市,102.02,84.85,122.55,...,138.75,115.16,121.43,NaN,1300000.0,NaN,NaN,NaN,NaN,NaN
7225,2018,万年县,361129,36,江西省,3611,上饶市,104.65,87.49,132.92,...,153.27,116.54,109.98,NaN,1300000.0,NaN,NaN,NaN,NaN,NaN
7226,2018,万源市,511781,51,四川省,5117,达州市,100.01,87.19,115.75,...,131.30,111.92,113.78,1100000.0,1400000.0,33836.0,0.412048,NaN,NaN,NaN

In [80]:
df_2018.iloc[:,8:].dtypes

coverage_breadth        float64
usage_depth             float64
payment                 float64
insurance               float64
monetary_fund           float64
investment              float64
credit                  float64
credit_investigation    float64
digitization_level      float64
flb                     float64
gdp                     float64
per_gdp                 float64
urban                   float64
industry                float64
ip                      float64
tradeopeness            float64
dtype: object

In [81]:
imp = SimpleImputer(missing_values=np.nan, strategy='median')
df_2018.iloc[:,8:]= imp.fit_transform(df_2018.iloc[:,8:])

/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())

In [55]:
# df_2018 = df_2018.fillna(lambda x: x.median())

In [82]:
df_2018.isnull().sum()

year                    0
county_name             0
county_code_year14      0
prov_code               0
prov_name               0
pref_code               0
pref_name               1
index_aggregate         0
coverage_breadth        0
usage_depth             0
payment                 0
insurance               0
monetary_fund           0
investment              0
credit                  0
credit_investigation    0
digitization_level      0
flb                     0
gdp                     0
per_gdp                 0
urban                   0
industry                0
ip                      0
tradeopeness            0
dtype: int64

In [89]:
df = data.copy()

In [90]:
df.head()

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
0,2014,万全县,130729,13,河北省,1307,张家口市,44.58,52.42,37.77,...,35.34,NaN,31.04,528889.0,634602.0,NaN,NaN,0.432618,0.064318,0.010522
1,2014,万安县,360828,36,江西省,3608,吉安市,44.39,33.21,78.26,...,85.27,NaN,19.80,341328.0,575617.0,NaN,NaN,NaN,NaN,NaN
2,2014,万年县,361129,36,江西省,3611,上饶市,47.34,42.86,60.84,...,57.87,NaN,37.63,644512.0,1000000.0,NaN,NaN,NaN,NaN,NaN
3,2014,万源市,511781,51,四川省,5117,达州市,41.67,46.64,41.19,...,45.24,NaN,26.13,574068.0,1200000.0,28395.0,0.561833,NaN,0.078333,0.005540
4,2014,万荣县,140822,14,山西省,1408,运城市,45.07,48.69,44.57,...,62.17,NaN,34.01,359126.0,618199.0,13778.0,0.069839,NaN,NaN,NaN

In [120]:
import numpy as np
from sklearn.impute import SimpleImputer
def imputer(df):
    imp = SimpleImputer(missing_values=np.nan, strategy='median')
    df.iloc[:,19:] = imp.fit_transform(df.iloc[:,19:])
    return df

for i in df.year.value_counts().index:

    df[df.year==i] = imputer(df[df.year==i])
df

/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
/Users/katie/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/core/indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())

,year,county_name,county_code_year14,prov_code,prov_name,pref_code,pref_name,index_aggregate,coverage_breadth,usage_depth,...,credit,credit_investigation,digitization_level,flb,gdp,per_gdp,urban,industry,ip,tradeopeness
0,2014,万全县,130729,13,河北省,1307,张家口市,44.58,52.42,37.77,...,35.34,NaN,31.04,528889.0,634602.0,27323.0,0.214560,0.432618,0.064318,0.010522
1,2014,万安县,360828,36,江西省,3608,吉安市,44.39,33.21,78.26,...,85.27,NaN,19.80,341328.0,575617.0,27323.0,0.214560,0.361632,0.106056,0.031628
2,2014,万年县,361129,36,江西省,3611,上饶市,47.34,42.86,60.84,...,57.87,NaN,37.63,644512.0,1000000.0,27323.0,0.214560,0.361632,0.106056,0.031628
3,2014,万源市,511781,51,四川省,5117,达州市,41.67,46.64,41.19,...,45.24,NaN,26.13,574068.0,1200000.0,28395.0,0.561833,0.361632,0.078333,0.005540
4,2014,万荣县,140822,14,山西省,1408,运城市,45.07,48.69,44.57,...,62.17,NaN,34.01,359126.0,618199.0,13778.0,0.069839,0.361632,0.106056,0.031628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9115,2018,龙游县,330825,33,浙江省,3308,衢州市,114.62,96.51,145.42,...,168.40,127.30,118.46,2900000.0,2400000.0,64909.0,0.324884,0.366683,0.193353,0.129952
9116,2018,龙胜各族自治县,450328,45,广西壮族自治区,4503,桂林市,104.15,88.98,123.98,...,141.65,118.02,118.19,494200.0,567484.0,35182.0,0.324884,0.269670,0.212241,0.237948
9117,2018,龙里县,522730,52,贵州省,5227,黔南布依族苗族自治州,108.30,98.59,123.06,...,152.02,115.11,113.57,1300000.0,1000000.0,62520.0,0.324884,0.490022,0.193353,0.237948
9118,2018,龙门县,441324,44,广东省,4413,惠州市,111.39,95.06,139.00,...,162.03,132.36,115.13,1200000.0,1700000.0,55476.0,0.324884,0.269670,0.193353,0.237948
9119,2018,龙陵县,530523,53,云南省,5305,保山市,98.30,85.18,112.77,...,124.92,107.30,115.32,1200000.0,826500.0,28227.0,0.115637,0.269670,0.193353,0.237948

In [95]:
type(res)

pandas.core.series.Series

In [121]:
df_2014.isnull().sum()

year                       0
county_name                0
county_code_year14         0
prov_code                  0
prov_name                  0
pref_code                  0
pref_name                  0
index_aggregate            0
coverage_breadth           0
usage_depth                0
payment                    0
insurance                  0
monetary_fund              0
investment                 0
credit                     0
credit_investigation    1720
digitization_level         0
flb                        1
gdp                        1
per_gdp                  493
urban                   1111
industry                 964
ip                      1153
tradeopeness            1173
dtype: int64

In [118]:
df_2014.shape

(1720, 24)